language: cpp
compiler:
  - gcc
  - clang
script: ./configure && make && make check
notifications:
  irc:
    channels:
      - "irc.freenode.org#communi"
    template:
      - "Build details: %{build_url}"
